//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charrmander.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Charrmander.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .charr.
        /// </summary>
        internal static string cfgFileExtension {
            get {
                return ResourceManager.GetString("cfgFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charrmander Character File (.charr)|*.charr.
        /// </summary>
        internal static string cfgFileFilter {
            get {
                return ResourceManager.GetString("cfgFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GW2 Character List.
        /// </summary>
        internal static string cfgFileName {
            get {
                return ResourceManager.GetString("cfgFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bitbucket.org/jokum/charrmander/raw/tip/VersionHistory.xml.
        /// </summary>
        internal static string cfgUpdateCheckUri {
            get {
                return ResourceManager.GetString("cfgUpdateCheckUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/charr.xsd.
        /// </summary>
        internal static string cfgXsdpath {
            get {
                return ResourceManager.GetString("cfgXsdpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are trying to load could not be found..
        /// </summary>
        internal static string msgOpenFailedNoFileBody {
            get {
                return ResourceManager.GetString("msgOpenFailedNoFileBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string msgOpenFailedNoFileTitle {
            get {
                return ResourceManager.GetString("msgOpenFailedNoFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are trying to load contains errors and could not be opened..
        /// </summary>
        internal static string msgOpenFailedParsingBody {
            get {
                return ResourceManager.GetString("msgOpenFailedParsingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Error.
        /// </summary>
        internal static string msgOpenFailedParsingTitle {
            get {
                return ResourceManager.GetString("msgOpenFailedParsingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not a GW2 Charrmander character list file..
        /// </summary>
        internal static string msgOpenFailedValidationBody {
            get {
                return ResourceManager.GetString("msgOpenFailedValidationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string msgOpenFailedValidationTitle {
            get {
                return ResourceManager.GetString("msgOpenFailedValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will write to the system registry. Do you wish to proceed?.
        /// </summary>
        internal static string msgRegisterExtensionBody {
            get {
                return ResourceManager.GetString("msgRegisterExtensionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register File Association.
        /// </summary>
        internal static string msgRegisterExtensionTitle {
            get {
                return ResourceManager.GetString("msgRegisterExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already open. Would you like to reload it?.
        /// </summary>
        internal static string msgReloadFileBody {
            get {
                return ResourceManager.GetString("msgReloadFileBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload file?.
        /// </summary>
        internal static string msgReloadFileTitle {
            get {
                return ResourceManager.GetString("msgReloadFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes. Are you sure you wish to discard and exit?.
        /// </summary>
        internal static string msgUnsavedExitBody {
            get {
                return ResourceManager.GetString("msgUnsavedExitBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes and exit?.
        /// </summary>
        internal static string msgUnsavedExitTitle {
            get {
                return ResourceManager.GetString("msgUnsavedExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Are you sure you wish to open a file? Doing so will discard all unsaved changes..
        /// </summary>
        internal static string msgUnsavedOpenBody {
            get {
                return ResourceManager.GetString("msgUnsavedOpenBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard unsaved changes and open?.
        /// </summary>
        internal static string msgUnsavedOpenTitle {
            get {
                return ResourceManager.GetString("msgUnsavedOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to {0}:
        ///{1}.
        /// </summary>
        internal static string msgUpdateCheckFailedBody404 {
            get {
                return ResourceManager.GetString("msgUpdateCheckFailedBody404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the version history file..
        /// </summary>
        internal static string msgUpdateCheckFailedBodyReading {
            get {
                return ResourceManager.GetString("msgUpdateCheckFailedBodyReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: {0}.
        /// </summary>
        internal static string msgUpdateCheckFailedBodyUnknown {
            get {
                return ResourceManager.GetString("msgUpdateCheckFailedBodyUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check Failed.
        /// </summary>
        internal static string msgUpdateCheckFailedTitle {
            get {
                return ResourceManager.GetString("msgUpdateCheckFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no update available..
        /// </summary>
        internal static string msgUpdateCheckNoUpdatesBody {
            get {
                return ResourceManager.GetString("msgUpdateCheckNoUpdatesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update Available.
        /// </summary>
        internal static string msgUpdateCheckNoUpdatesTitle {
            get {
                return ResourceManager.GetString("msgUpdateCheckNoUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} - Charrmander.
        /// </summary>
        internal static string wnWindowTitle {
            get {
                return ResourceManager.GetString("wnWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://charr.org.
        /// </summary>
        internal static string xNamespace {
            get {
                return ResourceManager.GetString("xNamespace", resourceCulture);
            }
        }
    }
}
